### ISSUE TITLE
batch put()

### ISSUE THREAD

**Issue by qizhou** [ethstorage/storage-contracts-v1#17]
We should offer batch put() and compare the gas with one-by-one put()'s

**Comment by syntrust** [comment]
Test results against [putBlobs](https://github.com/ethstorage/storage-contracts-v1/blob/b14166d4b4abe8ccc546e3bcff7f87cc6743924d/contracts/TestEthStorageContractKZG.sol#L46) shows one-by-one (putBlob) wins:
|method called|blobs per tx|first tx gas used|later tx gas used|average gas used per tx| 
| ---- | ---- | ---- | ---- |---- |
|putBlob|1|128,113|31,680|31680|
|putBlobs|1|129,679|92,404|92404|
|putBlobs|2|188,459|151,196|75598|
|putBlobs|3|247,076|209,801|69934|
|putBlobs|4|305,033|268,606|67151|
|putBlobs|5|365,216|327,941|65588|
|putBlobs|6|424,751|387,452|64575|

**Comment by qizhou** [comment]
I think there is space for optimization for putBlobs: e.g., _putInternal() should have a batch version (as the current implementation for fee calculation is also wrong)

**Comment by qizhou** [comment]
> Test results against [putBlobs](https://github.com/ethstorage/storage-contracts-v1/blob/b14166d4b4abe8ccc546e3bcff7f87cc6743924d/contracts/TestEthStorageContractKZG.sol#L46) shows one-by-one (putBlob) wins:
> 
> method called	blobs per tx	first tx gas used	later tx gas used	average gas used per tx
> putBlob	1	128,113	31,680	31680
> putBlobs	1	129,679	92,404	92404
> putBlobs	2	188,459	151,196	75598
> putBlobs	3	247,076	209,801	69934
> putBlobs	4	305,033	268,606	67151
> putBlobs	5	365,216	327,941	65588
> putBlobs	6	424,751	387,452	64575

where is the code to reproduce the number?  My quick estimate of putBlob using `npm test` should be about `60,000` gas compared to ~`128,000`.

**Comment by syntrust** [comment]
> > Test results against [putBlobs](https://github.com/ethstorage/storage-contracts-v1/blob/b14166d4b4abe8ccc546e3bcff7f87cc6743924d/contracts/TestEthStorageContractKZG.sol#L46) shows one-by-one (putBlob) wins:
> > method called	blobs per tx	first tx gas used	later tx gas used	average gas used per tx
> > putBlob	1	128,113	31,680	31680
> > putBlobs	1	129,679	92,404	92404
> > putBlobs	2	188,459	151,196	75598
> > putBlobs	3	247,076	209,801	69934
> > putBlobs	4	305,033	268,606	67151
> > putBlobs	5	365,216	327,941	65588
> > putBlobs	6	424,751	387,452	64575
> 
> where is the code to reproduce the number? My quick estimate of putBlob using `npm test` should be about `60,000` gas compared to ~`128,000`.

https://github.com/ethstorage/es-node/blob/caef7d0c98fe44eddddae6711896ae43e5e50f20/integration_tests/kzg_prover_test.go#L69

**Comment by qizhou** [comment]
A couple of issues of the code are that
- it uses a smart contract deployed to access blob hash, which should be replaced by the OPCODE with 3 gas #62 
- I am not sure it last_kv_value is 0 in the test, as it will take additional 20,000 gas compared to non-zero case.

**Comment by syntrust** [comment]
Update tests for `putBlob` with different key each time:  first blob 117,274, later 98074. Make sense for 20,000 gas diff.

**Comment by syntrust** [comment]
After [use blobhash()](https://github.com/ethstorage/storage-contracts-v1/pull/68):
first 110,306. later 93187
