### ISSUE TITLE
optimization: build a circuit to verify multiple sampling on multiple blobs

### ISSUE THREAD

**Issue by qizhou** [ethstorage/storage-contracts-v1#20]
Currently, we have a circuit to verify a simple from a single blob.  If we want to verify multiple samples in a check, we have to call the blob encoder verifier numerous times, which is costly.  A simple way may implement a circuit to verify multiple samples with multiple blob encoder circuits

**Comment by qzhodl** [comment]
Two verifyDecoding call gas cost with **the current circuit**: 2 * 221128 = 442,256
One verifyDecoding call gas cost with **the new circuit**: 212,967

Proof tx gas cost now: 681,465
Total saving gas: 229,289 which is **33%** of the proof tx gas

**Comment by qzhodl** [comment]
https://github.com/ethstorage/storage-contracts-v1/pull/47 fixed it. @syntrust could you please share the gas comparison between the new and old circuit?

**Comment by syntrust** [comment]
> #47 fixed it. @syntrust could you please share the gas comparison between the new and old circuit?

|Circuit|Gas|
|--|--|
|old|572,610|
|new|372,882|
|saved|34.9%|
