### ISSUE TITLE
Failed to obtain blockhash

### ISSUE THREAD

**Issue by syntrust** [ethstorage/storage-contracts-v1#28]
Sometimes the es-node miner will hit "failed to obtain blockhash" when submitting a mining transaction - meaning `blockhash(blockNumber)` returns 0.

Environment: 
- L1: `dencun-devnet-9`
- contract: v0.1.0
- es-node: v0.1.0

**Comment by syntrust** [comment]
It turns out the `blockNumber` passed into function `mine()` somehow is the current block number (`block.number`) , or even bigger?

Changes made to the contract are as follows:
```
        require(block.number - blockNumber <= 64, "block number too old");
        require(block.number > blockNumber, "is current block number!");
        bytes32 bh = blockhash(blockNumber);
```
And we can see occasionally the error `"is current block number!"` during mining tests.

**Comment by qzhodl** [comment]
So the root cause is the chain reorg?

**Comment by syntrust** [comment]
A block number happened twice, so it looks like there was a reorg.

**Comment by syntrust** [comment]
As the time to generate zk-SNARK proofs decreases, a recent test reproduced the failure on Sepolia:

```
INFO [02-04|08:21:25.383] Updating tasks with L1 new head          blockNumber=5,216,434 blockTime=1,707,031,284 blockHash=164b29..308db6 now=1,707,031,285
INFO [02-04|08:21:25.405] Download range                           cache=true    start=5,216,434 end=5,216,434 blobNumber=0 duration(ms)=22
INFO [02-04|08:21:25.406] Mining info retrieved                    shard=0 lastMineTime=1,707,030,324 difficulty=10,036,224 proofsSubmitted=22
INFO [02-04|08:21:25.406] Mining tasks assigned                    shard=0 threads=64 block=5,216,434 nonces=1,048,576
INFO [02-04|08:21:25.688] The nonces are exhausted in this slot, waiting for the next block samplingTime=0.3s shard=0 block=5,216,434
INFO [02-04|08:21:25.723] Calculated a valid hash                  shard=0 thread=6  block=5,216,434 nonce=114,063
INFO [02-04|08:21:25.746] Get data hash                            kvIndex=5 hash=0x0000000000000000000000000000000000000000000000000000000000000000
INFO [02-04|08:21:25.746] Get data hash                            kvIndex=2 hash=0x0000000000000000000000000000000000000000000000000000000000000000
INFO [02-04|08:21:25.820] Got sample data                          shard=0 thread=6  block=5,216,434 kvIdxs="[5 2]" sampleIdxsInKv="[3357 593]"
INFO [02-04|08:21:34.970] Generate zk proof done                   sampleIdx="[3357 593]"  timeUsed(s)=8.028
INFO [02-04|08:21:34.970] Got storage proof                        shard=0 thread=6  block=5,216,434 kvIdx="[5 2]" sampleIdxsInKv="[3357 593]"
INFO [02-04|08:21:34.970] Set mining result                        shard=0 block=5,216,434 nonce=114,063
INFO [02-04|08:21:34.970] Mine task success                        shard=0 thread=6  block=5,216,434
INFO [02-04|08:21:34.970] Mining result loop get result            shard=0 block=5,216,434 nonce=114,063
INFO [02-04|08:21:35.013] Query gas price done                     gasPrice=3,280,973,591
INFO [02-04|08:21:35.036] Query gas tip cap done                   gasTipGap=100,000
ERROR[02-04|08:21:35.063] Estimate gas failed                      error="execution reverted: is current block number"
INFO [02-04|08:21:35.084] Query most recent block                  blockNumber=5,216,434 blockTime=1,707,031,284 blockHash=164b29..308db6
ERROR[02-04|08:21:35.085] Failed to submit mined result            shard=0 block=5,216,434 error="failed to estimate gas: execution reverted: is current block number"
INFO [02-04|08:21:35.403] P2P Summary                              activePeers=0 inbound=0 outbound=0

```

The block can be confirmed was not reorged from the etherscan: https://sepolia.etherscan.io/block/5216434

Changes to the contract:
```
require(block.number - blockNumber <= 64, "block number too old");
require(block.number - blockNumber != 0, "is current block number");
require(block.number - blockNumber > 0, "block number too new");
```

**Comment by qzhodl** [comment]
> INFO [02-04|08:21:35.084] Query most recent block                  blockNumber=5,216,434 blockTime=1,707,031,284 blockHash=164b29..308db6

I guess that when a node receives a proposed block, it broadcasts this message to all connected clients immediately. If we attempt to estimate the gas while still within the same slot, Geth will likely use the current block number for this estimation, given that the next slot hasn't yet arrived.

To address this, we could wait for 12 seconds and then try the estimation again to see if the error persists.

**Comment by qizhou** [comment]
I forget some context - what is the reason for `require(block.number - blockNumber != 0, "is current block number");`?

**Comment by syntrust** [comment]
> I forget some context - what is the reason for `require(block.number - blockNumber != 0, "is current block number");`?

To confirm that `blockNumber` is `block.number` in which case `blockhash(blockNumber)` returns 0 which prevents the difficulty check.

**Comment by qzhodl** [comment]
https://github.com/ethstorage/es-node/pull/181 is trying to fix this issue

**Comment by syntrust** [comment]
This issue is resolved in https://github.com/ethstorage/es-node/pull/293, where `PollingClient.getLatestHeader()` chooses the sub-latest block. So the change in https://github.com/ethstorage/es-node/pull/181 should revert.

**Comment by syntrust** [comment]
A new fix https://github.com/ethstorage/es-node/pull/487 is based on this fact that can be verified with a simple test:

1. The current block number `blockNumber` is used as `block.number` for `eth_estimateGas`, so `blockhash(blockNumber)` is not available.
2. For `eth_sendTransaction`, `blockNumber` + 1 is considered as `block.number`, and `blockhash(blockNumber)` is available.
