### ISSUE TITLE
Need to determine better randomness for sampling

### ISSUE THREAD

**Issue by qizhou** [ethstorage/storage-contracts-v1#32]
We currently use block header hash as the entropy of the randomness for sampling, where block header hash may be prone to grinding attack.  We may need to find a better random source such as RANDAO or VDF.

**Comment by qizhou** [comment]
https://eth2book.info/capella/part2/building_blocks/randomness/

**Comment by qizhou** [comment]
We may need to consider this in devnet-3.

**Comment by qzhodl** [comment]
It seems that we can only access the current RANDAO by using block.prevrandao, but can not get RANDAO value at specific block in evm according to [1](https://github.com/ethereum/EIPs/issues/5677) and [2](https://ethereum-magicians.org/t/eip-4399-supplant-difficulty-opcode-with-random/7368/49).

**Comment by qizhou** [comment]
What is the current block hash generation mechanism?  We can face a grinding attack if it can be changed easily.

For RANDAO, we can use header hash + proof to show that the RANDAO of a block header.

**Comment by qizhou** [comment]
#60
