### ISSUE TITLE
Need a way to transfer the treasury token to pay the prepaid amount automactically

### ISSUE THREAD

**Issue by qzhodl** [ethstorage/storage-contracts-v1#54]
# Rationale

Three cases need to be considered:
1. Where does the initial prepaid amount come from when creating the first shard
2. How about increasing the shard size after the first shard is created
3. How to handle it when creating the second shard

**Comment by syntrust** [comment]
Solved by https://github.com/ethstorage/storage-contracts-v1/pull/110
