### ISSUE TITLE
Some config can be immutable to save gas

### ISSUE THREAD

**Issue by qizhou** [ethstorage/storage-contracts-v1#70]
# Rationale
Some constant variables used in `put()` path can be replaced by immutable and save gas:

- `shardEntryBits`
- `storageCost`
- `startTime`
- `dcfFactor`
- `maxKvSize`

This will save about 2100 * 5 = 10500 gas per put()

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by qzhodl** [comment]
Reference:
1. https://github.com/wighawag/clones-with-immutable-args
2. An idea is to use ClonesWithImmutableArgs.sol (employed by OP) https://goerli.etherscan.io/address/0x666C3d298B9c360990F901b3Eded4e7a9d7AD446#code#F2#L5

**Comment by iteyelmp** [comment]
Has been fixed
