### ISSUE TITLE
Improve the coding style of the storage contract

### ISSUE THREAD

**Issue by qizhou** [ethstorage/storage-contracts-v1#75]
#### System information

Our contract's coding style can be improved:
- More comments
- Variable naming
- Better error handling

A better example is Optimism's contract and their style guide.
https://github.com/ethstorage/optimism/blob/develop/packages/contracts-bedrock/STYLE_GUIDE.md

Commit hash : <commit>

**Comment by qzhodl** [comment]
https://github.com/ethstorage/storage-contracts-v1/pull/95
