### ISSUE TITLE
Incorrect block header items used in prover.js `generateRandaoProof()`

### ISSUE THREAD

**Issue by alexbabits** [ethstorage/storage-contracts-v1#84]
### Location of Problem
https://github.com/ethstorage/storage-contracts-v1/blob/f1c9c17ef16b59c0495388672f11797eeec7848a/test/lib/prover.js#L30

### Problem
Block header items are not correct for current blocks (Cancun era), this would lead to incorrect block hash recreation.

### Solution
See this post, scroll to bottom: https://ethereum.stackexchange.com/questions/163229/how-to-verify-block-hash-post-merge-block-15-5m. 

My concern is that the `generateRandaoProof()` is incorrect, because it does not match what I found to be the correct block header items needed to recreate the block hash from a block header.

**Comment by qizhou** [comment]
The block hash should be correct, and `generateRandaoProof()` misses some fields introduced in Cancun.  A quick fix in #85 will add these field in the header.

**Comment by syntrust** [comment]
Another fix https://github.com/ethstorage/storage-contracts-v1/pull/90 is merged to handle the zero number correctly.
